# Tarea 10
### Nombre: David Alejandro Díaz Pineda

# 1)

In [4]:
import numpy as np

Realice las siguientes multiplicaciones matriz-matriz:

a.
 $$
\begin{bmatrix}
2 & -3  \\
3 & -1  \\
\end{bmatrix}

\begin{bmatrix}
1 & 5  \\
2 & 0  \\
\end{bmatrix}
$$


In [5]:
A = np.array([[2, -3],
              [3, -1]])

B = np.array([[1, 5],
              [2, 0]])

C = A @ B
print(C)


[[-4 10]
 [ 1 15]]


b. 
$$
\begin{bmatrix}
2 & -3 \\
3 & -1  \\
\end{bmatrix}

\begin{bmatrix}
1 & 5 & -4 \\
-3 & 2 & 0 \\
\end{bmatrix}
$$

In [6]:
A = np.array([[2, -3],
              [3, -1]])

B = np.array([[1, 5, -4],
              [-3, 2, 0]])

C = A @ B
print(C)

[[ 11   4  -8]
 [  6  13 -12]]


c. 
$$
\begin{bmatrix}
2 & -3 & 1 \\
4 & 3 & 0 \\
5 & 2 & -4
\end{bmatrix}

\begin{bmatrix}
0 & 1 & -2 \\
1 & 0 & -1 \\
2 & 3 & -2
\end{bmatrix}
$$

In [7]:
A = np.array([[2, -3, 1],
              [4, 3, 0],
              [5, 2, -4]])

B = np.array([[0, 1, -2],
              [1, 0, -1],
              [2, 3, -2]])

C = A @ B
print(C)

[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


d.
$$
\begin{bmatrix}
2 & 1 & 2 \\
-2 & 3 & 0 \\
2 & -1 & 3
\end{bmatrix}

\begin{bmatrix}
1 & 2 \\
-4 & 1 \\
0 & 2 
\end{bmatrix}
$$

In [8]:
A = np.array([[2, 1, 2],
              [-2, 3, 0],
              [2, -1, 3]])

B = np.array([[1, -2],
              [-4, 1],
              [0, 2]])

C = A @ B
print(C)

[[ -2   1]
 [-14   7]
 [  6   1]]
