# Tarea 10
### Nombre: David Alejandro Díaz Pineda

In [126]:
# ----------------------------- logging --------------------------
import logging
from sys import stdout
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[01-24 20:05:55][INFO] 2026-01-24 20:05:55.154419


# 1)

In [127]:
import numpy as np

Realice las siguientes multiplicaciones matriz-matriz:

a.
 $$
\begin{bmatrix}
2 & -3  \\
3 & -1  \\
\end{bmatrix}

\begin{bmatrix}
1 & 5  \\
2 & 0  \\
\end{bmatrix}
$$


In [128]:
A = np.array([[2, -3],
              [3, -1]])

B = np.array([[1, 5],
              [2, 0]])

C = A @ B
print(C)


[[-4 10]
 [ 1 15]]


b. 
$$
\begin{bmatrix}
2 & -3 \\
3 & -1  \\
\end{bmatrix}

\begin{bmatrix}
1 & 5 & -4 \\
-3 & 2 & 0 \\
\end{bmatrix}
$$

In [129]:
A = np.array([[2, -3],
              [3, -1]])

B = np.array([[1, 5, -4],
              [-3, 2, 0]])

C = A @ B
print(C)

[[ 11   4  -8]
 [  6  13 -12]]


c. 
$$
\begin{bmatrix}
2 & -3 & 1 \\
4 & 3 & 0 \\
5 & 2 & -4
\end{bmatrix}

\begin{bmatrix}
0 & 1 & -2 \\
1 & 0 & -1 \\
2 & 3 & -2
\end{bmatrix}
$$

In [130]:
A = np.array([[2, -3, 1],
              [4, 3, 0],
              [5, 2, -4]])

B = np.array([[0, 1, -2],
              [1, 0, -1],
              [2, 3, -2]])

C = A @ B
print(C)

[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]


d.
$$
\begin{bmatrix}
2 & 1 & 2 \\
-2 & 3 & 0 \\
2 & -1 & 3
\end{bmatrix}

\begin{bmatrix}
1 & 2 \\
-4 & 1 \\
0 & 2 
\end{bmatrix}
$$

In [131]:
A = np.array([[2, 1, 2],
              [-2, 3, 0],
              [2, -1, 3]])

B = np.array([[1, -2],
              [-4, 1],
              [0, 2]])

C = A @ B
print(C)

[[ -2   1]
 [-14   7]
 [  6   1]]


# 2)

Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices: 

In [132]:
# ####################################################################
def gauss_jordan(A: np.ndarray) -> np.ndarray:
    """Realiza la eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(k), donde n es el número de incógnitas.

    ## Return

    ``A``: matriz reducida por filas.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    n = A.shape[0]

    for i in range(0, n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux

        # --- Eliminación: loop por fila
        # for j in range(i + 1, n): # Eliminación gaussiana
        for j in range(n):  # Gauss-Jordan
            if j == i:
                continue  # skip pivot row

            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

            # dividir para la diagonal
        A[i, :] = A[i, :] / A[i, i]

        logging.info(f"\n{A}")

    if A[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

  

    return A

In [133]:
def matriz_inversa(A: np.ndarray) -> np.ndarray:
    """Calcula la matriz inversa de A usando eliminación de Gauss-Jordan

    ## Parameters

    ``A``: matriz cuadrada a invertir.

    ## Return

    ``A_inv``: matriz inversa de A.

    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)

    n = A.shape[0]
   
    A_aumentada = np.hstack((A, np.eye(n)))

    A_reducida = gauss_jordan(A_aumentada)

    A_inversa = A_reducida[:, n:]

    return A_inversa    

In [134]:
import numpy as np

def es_no_singular_numpy(A):
    return np.linalg.det(A) != 0


a.
$$
\begin{bmatrix}
4 & 2 & 6 \\
3 & 0 & 7 \\
-2 & -1 & -3
\end{bmatrix}

$$

In [135]:
A = np.array([[4, 2, 6],
              [3, 0, 7],
              [-2, -1, -3]])

In [136]:
es_no_singular_numpy(A)

np.False_

b.
$$
\begin{bmatrix}
1 & 2 & 0 \\
2 & 1 & -1 \\
3 & 1 & 1
\end{bmatrix}

$$

In [137]:
B = np.array([[1, 2, 0],
              [2, 1, -1],
              [3, 1, 1]])

In [138]:
es_no_singular_numpy(B)

np.True_

In [139]:
matriz_inversa(B)

[01-24 20:05:55][INFO] 
[[ 1.  2.  0.  1.  0.  0.]
 [ 0. -3. -1. -2.  1.  0.]
 [ 0. -5.  1. -3.  0.  1.]]
[01-24 20:05:55][INFO] 
[[ 1.          0.         -0.66666667 -0.33333333  0.66666667  0.        ]
 [-0.          1.          0.33333333  0.66666667 -0.33333333 -0.        ]
 [ 0.          0.          2.66666667  0.33333333 -1.66666667  1.        ]]
[01-24 20:05:55][INFO] 
[[ 1.     0.     0.    -0.25   0.25   0.25 ]
 [-0.     1.     0.     0.625 -0.125 -0.125]
 [ 0.     0.     1.     0.125 -0.625  0.375]]


array([[-0.25 ,  0.25 ,  0.25 ],
       [ 0.625, -0.125, -0.125],
       [ 0.125, -0.625,  0.375]])

c.
$$
\begin{bmatrix}
1 & 1 & -1 & 1 \\
1 & 2 & -4 & -2 \\
2 & 1 & 1 & 5 \\
-1 & 0 & -2 & -4
\end{bmatrix}


$$

In [140]:
C= np.array([[1, 1, -1, 1],
                [1, 2, -4, -2],
                [2, 1, 1, 5],
                [-1, 0, -2, -4]])

In [141]:
es_no_singular_numpy(C)

np.False_

d.
$$
\begin{bmatrix}
4 & 0 & 0 & 0 \\
6 & 7 & 0 & 0 \\
9 & 11 & 1 & 0 \\
5 & 4 & 1 & 1
\end{bmatrix}
$$

In [142]:
D = np.array([[4, 0, 0, 0],
                [6, 7, 0, 0],
                [9, 11, 1, 0],
                [5, 4, 1, 1]])

In [143]:
es_no_singular_numpy(D)

np.True_

In [144]:
matriz_inversa(D)

[01-24 20:05:56][INFO] 
[[ 1.    0.    0.    0.    0.25  0.    0.    0.  ]
 [ 0.    7.    0.    0.   -1.5   1.    0.    0.  ]
 [ 0.   11.    1.    0.   -2.25  0.    1.    0.  ]
 [ 0.    4.    1.    1.   -1.25  0.    0.    1.  ]]
[01-24 20:05:56][INFO] 
[[ 1.      0.      0.      0.      0.25    0.      0.      0.    ]
 [ 0.      1.      0.25    0.25   -0.3125  0.      0.      0.25  ]
 [ 0.      0.     -1.75   -2.75    1.1875  0.      1.     -2.75  ]
 [ 0.      0.     -1.75   -1.75    0.6875  1.      0.     -1.75  ]]
[01-24 20:05:56][INFO] 
[[ 1.          0.          0.          0.          0.25        0.
   0.          0.        ]
 [ 0.          1.          0.         -0.14285714 -0.14285714  0.
   0.14285714 -0.14285714]
 [-0.         -0.          1.          1.57142857 -0.67857143 -0.
  -0.57142857  1.57142857]
 [ 0.          0.          0.          1.         -0.5         1.
  -1.          1.        ]]
[01-24 20:05:56][INFO] 
[[ 1.          0.          0.          0.          0.25  

array([[ 0.25      ,  0.        ,  0.        ,  0.        ],
       [-0.21428571,  0.14285714,  0.        ,  0.        ],
       [ 0.10714286, -1.57142857,  1.        ,  0.        ],
       [-0.5       ,  1.        , -1.        ,  1.        ]])

# 3)

Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes: 

In [145]:
from src import descomposicion_LU, resolver_LU

In [146]:
A = np.array([[1, -1, 2, -1],
                [1, 0, -1, 1],
                [2, 1, 3, -4],
                [0, -1, 1, -1]])

$x_1 - x_2 + 2x_3 - x_4 = 6$<br> 
$x_1 - x_3 + x_4 = 4$ <br>
$2x_1 + x_2 + 3x_3 - 4x_4 = -2$ <br>
$-x_2 + x_3 - x_4 = 5$



$$b1=
\begin{bmatrix}
6\\
4 \\
-2 \\
5
\end{bmatrix}
$$

In [147]:
L1, U1 = descomposicion_LU(np.array(A))
b1 = np.array([6,4,-2,5])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema Ax=b:")
print(x1)

[01-24 20:05:56][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  3. -1. -2.]
 [ 0. -1.  1. -1.]]
[01-24 20:05:56][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0. -2.  1.]]
[01-24 20:05:56][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-24 20:05:56][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-24 20:05:56][INFO] Sustitución hacia adelante
[01-24 20:05:56][INFO] y = 
[[ 6.]
 [-2.]
 [-8.]
 [ 1.]]
[01-24 20:05:56][INFO] Sustitución hacia atrás
[01-24 20:05:56][INFO] i = 2
[01-24 20:05:56][INFO] suma = [8.]
[01-24 20:05:56][INFO] U[i, i] = 8.0
[01-24 20:05:56][INFO] y[i] = [-8.]
[01-24 20:05:56][INFO] i = 1
[01-24 20:05:56][INFO] suma = [4.]
[01-24 20:05:56][INFO] U[i, i] = 1.0
[01-24 20:05:56][INFO] y[i] = [-2.]
[01-24 20:05:56][INFO] i = 0
[01-24 20:05:56][INFO] suma = [3.]
[01-24 20:05:56][INFO] U[i, i] = 1.0
[01-24 20:05:56][INFO] y[i] = [6.]
Matriz L:
[[ 1.    0.    0.    0

$x_1 - x_2 + 2x_3 - x_4 = 1$<br>
$x_1 - x_3 + x_4 = 1$<br>
$2x_1 + x_2 + 3x_3 - 4x_4=2$ <br>
$-x_2 + x_3 - x_4 = -1$

$$b1=
\begin{bmatrix}
1\\
1 \\
2 \\
-1
\end{bmatrix}
$$

In [148]:
L1, U1 = descomposicion_LU(np.array(A))
b1 = np.array([1,1,2,-1])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema Ax=b:")
print(x1)

[01-24 20:05:56][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  3. -1. -2.]
 [ 0. -1.  1. -1.]]
[01-24 20:05:56][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0. -2.  1.]]
[01-24 20:05:56][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-24 20:05:56][INFO] 
[[ 1. -1.  2. -1.]
 [ 0.  1. -3.  2.]
 [ 0.  0.  8. -8.]
 [ 0.  0.  0. -1.]]
[01-24 20:05:56][INFO] Sustitución hacia adelante
[01-24 20:05:56][INFO] y = 
[[ 1.]
 [ 0.]
 [ 0.]
 [-1.]]
[01-24 20:05:56][INFO] Sustitución hacia atrás
[01-24 20:05:56][INFO] i = 2
[01-24 20:05:56][INFO] suma = [-8.]
[01-24 20:05:56][INFO] U[i, i] = 8.0
[01-24 20:05:56][INFO] y[i] = [0.]
[01-24 20:05:56][INFO] i = 1
[01-24 20:05:56][INFO] suma = [-1.]
[01-24 20:05:56][INFO] U[i, i] = 1.0
[01-24 20:05:56][INFO] y[i] = [0.]
[01-24 20:05:56][INFO] i = 0
[01-24 20:05:56][INFO] suma = [0.]
[01-24 20:05:56][INFO] U[i, i] = 1.0
[01-24 20:05:56][INFO] y[i] = [1.]
Matriz L:
[[ 1.    0.    0.    0

# 4)

Encuentre los valores de A que hacen que la siguiente matriz sea singular. 

$$
\begin{bmatrix}
1 & -1 & \alpha \\
2 & 2 & 1 \\
0 & \alpha & -\frac{3}{2}
\end{bmatrix}

$$

# 5) 

Resuelva los siguientes sistemas lineales:

a. 
$$
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
-1 & 0 & 1
\end{bmatrix}

\begin{bmatrix}
2 & 3 & -1 \\
0 & -2 & 1 \\
0 & 0 & 3
\end{bmatrix}

\begin{bmatrix}
x_1  \\
x_2  \\
x_3 
\end{bmatrix} =

\begin{bmatrix}
2  \\
-1  \\
1
\end{bmatrix}
$$

In [154]:
A= np.array([[1, 0, 0],
                [2, 1, 0],
                [-1, 0, 1]])

B = np.array([[2, 3, -1],
                [0, -2, 1],
                [0, 0, 3]])

C = A @ B

In [150]:
L1, U1 = descomposicion_LU(np.array(C))
b1 = np.array([2,-1,1])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema Ax=b:")
print(x1)

[01-24 20:05:56][INFO] 
[[ 2.  3. -1.]
 [ 0. -2.  1.]
 [ 0.  0.  3.]]
[01-24 20:05:56][INFO] 
[[ 2.  3. -1.]
 [ 0. -2.  1.]
 [ 0.  0.  3.]]
[01-24 20:05:56][INFO] 
[[ 2.  3. -1.]
 [ 0. -2.  1.]
 [ 0.  0.  3.]]
[01-24 20:05:56][INFO] Sustitución hacia adelante
[01-24 20:05:56][INFO] y = 
[[ 2.]
 [-5.]
 [ 3.]]
[01-24 20:05:56][INFO] Sustitución hacia atrás
[01-24 20:05:56][INFO] i = 1
[01-24 20:05:56][INFO] suma = [1.]
[01-24 20:05:56][INFO] U[i, i] = -2.0
[01-24 20:05:56][INFO] y[i] = [-5.]
[01-24 20:05:56][INFO] i = 0
[01-24 20:05:56][INFO] suma = [8.]
[01-24 20:05:56][INFO] U[i, i] = 2.0
[01-24 20:05:56][INFO] y[i] = [2.]
Matriz L:
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1. -0.  1.]]
Matriz U:
[[ 2.  3. -1.]
 [ 0. -2.  1.]
 [ 0.  0.  3.]]
Solución del sistema Ax=b:
[[-3.]
 [ 3.]
 [ 1.]]


b. 
$$
\begin{bmatrix}
2 & 0 & 0 \\
-1 & 1 & 0 \\
3 & 2 & -1
\end{bmatrix}

\begin{bmatrix}
1 & 1 & 1 \\
0 & 1 & 2 \\
0 & 0 & 1
\end{bmatrix}

\begin{bmatrix}
x_1  \\
x_2  \\
x_3 
\end{bmatrix} =

\begin{bmatrix}
-1  \\
3  \\
0
\end{bmatrix}
$$

In [151]:
A= np.array([[2, 0, 0],
                [-1, 1, 0],
                [3, 2, -1]])

B = np.array([[1, 1, 1],
                [0, 1, 2],
                [0, 0, 1]])

C = A @ B

In [152]:
L1, U1 = descomposicion_LU(np.array(C))
b1 = np.array([-1,3,0])
x1 = resolver_LU(L1, U1, b1)
print("Matriz L:")
print(L1)
print("Matriz U:")
print(U1)   
print("Solución del sistema Ax=b:")
print(x1)

[01-24 20:05:56][INFO] 
[[2. 2. 2.]
 [0. 1. 2.]
 [0. 2. 3.]]
[01-24 20:05:56][INFO] 
[[ 2.  2.  2.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]
[01-24 20:05:56][INFO] 
[[ 2.  2.  2.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]
[01-24 20:05:56][INFO] Sustitución hacia adelante
[01-24 20:05:56][INFO] y = 
[[-1. ]
 [ 2.5]
 [-3.5]]
[01-24 20:05:56][INFO] Sustitución hacia atrás
[01-24 20:05:56][INFO] i = 1
[01-24 20:05:56][INFO] suma = [7.]
[01-24 20:05:56][INFO] U[i, i] = 1.0
[01-24 20:05:56][INFO] y[i] = [2.5]
[01-24 20:05:56][INFO] i = 0
[01-24 20:05:56][INFO] suma = [-2.]
[01-24 20:05:56][INFO] U[i, i] = 2.0
[01-24 20:05:56][INFO] y[i] = [-1.]
Matriz L:
[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 1.5  2.   1. ]]
Matriz U:
[[ 2.  2.  2.]
 [ 0.  1.  2.]
 [ 0.  0. -1.]]
Solución del sistema Ax=b:
[[ 0.5]
 [-4.5]
 [ 3.5]]


# 6)


Factorice las siguientes matrices en la descomposición LU mediante el algoritmo de factorización LU 
con lii = 1 para todas las i.